### ISSUE TITLE
Digits and symbols support

### ISSUE THREAD

**Issue by systems-rebooter** [uttesh/ngletteravatar#1]
Hey!

Awesome work! How can I add digit and symbols support to this? 

![screen shot 2015-06-21 at 14 09 15](https://cloud.githubusercontent.com/assets/8888190/8271421/4464d784-181f-11e5-829c-a044f7f78802.png)

Thanks!!

**Comment by uttesh** [comment]
Thanks @systems-rebooter .

nice feature, i will try to add that.

**Comment by systems-rebooter** [comment]
Thanks much @uttesh ;-) Impatiently waiting..

**Comment by uttesh** [comment]
@systems-rebooter  Added the feature now digits and special character will be support and have dynamic color apply as well. 

![numbers](https://cloud.githubusercontent.com/assets/2218611/8273132/3df134f2-187d-11e5-82ce-cf8f3432d96d.png)
![special_charaters](https://cloud.githubusercontent.com/assets/2218611/8273133/4a5dbd32-187d-11e5-90a7-eac26c74bf19.png)
![round_shape_digit_special](https://cloud.githubusercontent.com/assets/2218611/8273134/4f687fd8-187d-11e5-81bb-6bea8ad0a882.png)
![chinese](https://cloud.githubusercontent.com/assets/2218611/8273136/60cff634-187d-11e5-86ae-b740a0397245.png)
![kannada](https://cloud.githubusercontent.com/assets/2218611/8273137/60d8d678-187d-11e5-825d-631b9cd30008.png)
![round_chinese_kannada](https://cloud.githubusercontent.com/assets/2218611/8273138/610ad272-187d-11e5-8ced-e30118e15873.png)

all changes are updated in the bower package, do "bower update" or re-install the ngletteravatar.

**Comment by systems-rebooter** [comment]
That's so nice :)
