### ISSUE TITLE
First Name and last name...

### ISSUE THREAD

**Issue by Muthamizhan** [uttesh/ngletteravatar#16]
Hi i made a change in the library....
/**
<ng-letter-avatar data="Steve Jobs"></ng-letter-avatar>

var l=r.data.replace(/[^A-Z]/g, '').toUpperCase()

**/

to get first name and last name its working fine for me..please let me know its fine to use like this.

**Comment by uttesh** [comment]
Thanks @Muthamizhan, library is updated with that feature in 4.0.1. release.
