### ISSUE TITLE
Convert to pictures

### ISSUE THREAD

**Issue by systems-rebooter** [uttesh/ngletteravatar#2]
Hello, 

Is there easy way to convert to pictures those nice generated letters? 
I'm thinking about print-screening square ones, but that's too bad approach.. 

Thanks! 

upd: Basically a can do `save as` letters as svg vector image with transparent background, and then add appropriate background in image editor, which sounds like better approach. Not sure saving can be done with background image color..

**Comment by systems-rebooter** [comment]
Found a way.. 

http://techslides.com/save-svg-as-an-image

**Comment by uttesh** [comment]
cheers ;)
