### ISSUE TITLE
Does not display letters in phonegap/cordova on angular

### ISSUE THREAD

**Issue by jcbowyer** [uttesh/ngletteravatar#20]
I am trying to use the component in a phonegap application on angular but for some reason the letters do not display.  The circle does display.

**Comment by uttesh** [comment]
@jcbowyer Thanks, it should to be working i have tested on mobile framework ionic and phone gap, if possible provide codepen link with reported issue.

**Comment by jcbowyer** [comment]
I have a public alpha version of my website at http://caredareweb.azurewebsites.net/, you have to login to see the problem.  The image looks fine on the website.  It just does not show the letter when I run it on my android table from Dell.

**Comment by uttesh** [comment]
@jcbowyer  could please provide the test user or any demo user to test that, after registration i did not received activation email.

**Comment by jcbowyer** [comment]
I manually approved your account.  Let me if it works.

**Comment by uttesh** [comment]
could you please provide the credential details? or send detail to my email

**Comment by jcbowyer** [comment]
jcbowyer@yahoo.com password should work

**Comment by uttesh** [comment]
sorry could you please tell what is username and password?....username/password?

**Comment by jcbowyer** [comment]
Sorry I was not clear username:jcbowyer@yahoo.com password: password

**Comment by uttesh** [comment]
checked in my android phone looks fine. could you please provide more details like which browser u used to access the application from tablet?

![screenshot_2016-03-09-20-18-08](https://cloud.githubusercontent.com/assets/2218611/13638968/a67b6ed6-e634-11e5-904b-a773945b1bc8.png)

**Comment by uttesh** [comment]
@jcbowyer that tablet browser does not support html5 feature or svg image standards i guess. validate that supports html5 features?

**Comment by jcbowyer** [comment]
Yes it displays fine from the web.  If you compile it using cordova/phonegap and install it as an actual android application (.apk) file it does not display.  I am pretty sure it won't display any android device in an  cordova/phone gap application but I will have to confirm on a few different devices.

**Comment by uttesh** [comment]
i have used this directive in phone gap/ionic android apps its works fine there. let me validate once again.

**Comment by jcbowyer** [comment]
No worries.  If you have done it, I am sure it works and it is just my version of android browser.  Thanks again for your great work and support.

**Comment by Purus** [comment]
Just to clarify, it works in my Ionic framework.
