### ISSUE TITLE
Option when we have an picture

### ISSUE THREAD

**Issue by pablorsk** [uttesh/ngletteravatar#23]
Hi!

Your library is really great! But do you have a option when the user, for example, has a profile pricture?

Like Gmail, when don't have picture, put the LETTER, but when have, put the PICTURE.

The idea is use the same configuration for both cases, and don't generate a new code when we have a picture.

**Comment by uttesh** [comment]
@pablorsk  Thanks, I guess this can be done without modifying the library, anyways i will keep in my todo list.

**Comment by go96396** [comment]
Hi!

i just wanted to know is there any update on the above issue option when we have a picture. please let me know thanks.

**Comment by uttesh** [comment]
@pablorsk @go96396 library is updated with the changes. thanks,

**Comment by pablorsk** [comment]
@uttesh wooow! Great :). Now, we use your library in our project :)

**Comment by pablorsk** [comment]
Just a TIP:

When data is URL, `title` should be empty.

**Comment by uttesh** [comment]
@pablorsk updated with code cleanup, thanks.

**Comment by go96396** [comment]
thanks :-)
