### ISSUE TITLE
image url in data doesn't work

### ISSUE THREAD

**Issue by yeluolei** [uttesh/ngletteravatar#32]
set image url in data doesn't work like the demo shows

**Comment by uttesh** [comment]
@yeluolei  please provide more details, how u tried ? here is the code pen sample [http://codepen.io/uttesh/pen/LkXjLo](http://codepen.io/uttesh/pen/LkXjLo) its working fine

**Comment by yeluolei** [comment]
I am using the  npm install version, 4.0.2, it's not working .. seams that's the reason.
please help update the npm repository, thanks.

**Comment by uttesh** [comment]
@yeluolei  sorry about that, i have updated the npm package. thanks

**Comment by yeluolei** [comment]
@uttesh that's great. thank you~
