### ISSUE TITLE
Requirements for Ionic

### ISSUE THREAD

**Issue by adyba** [uttesh/ngletteravatar#6]
Hi, this module is a perfect fit for Ionic. After small changes I'm using it in one my project and it works like a charm. But there are two small complains that can be solved in about 5 LOCs. 
- First obvious change is the use of jQuery. I know you are using this with Bootstrap but once you change all the `$` for `angular.element` all the code is no more dependent on jQuery.
- Ionic uses avatars, but expects just plain `<img>'s` without all the wrappers. Thus the very end of the link function to be changed to mimic the deprecated (?) `replace:true` directive behavior. Simply<br>
  `<ng-letter-avatar data="Zimbra"></ng-letter-avatar>`<br>should compile just into<br>
  `<img src="data:image/svg+xml;base64,PHN2ZyB4bWxucz0iaHR0cDo..." style="">` 

Any of those changes should not harm your project, but Im not aware of the whole context. Do you want me to PR my changes or I should just fork into a `ngletteravatar for Ionic`?

**Comment by uttesh** [comment]
@adyba   Thanks for using plugin and valuable suggestion, i will make those changes.

**Comment by uttesh** [comment]
@adyba  updated the directive with only angular, removed jquery dependency and cleaned,organized the code. made latest release 3.0.0 which is available on bower.
