### ISSUE TITLE
Border radius should be in percent?

### ISSUE THREAD

**Issue by josteinhanssen** [uttesh/ngletteravatar#8]
I suggest changing the default setting for the border-radius to: 'border-radius:50%;'. This way it will always be a completly round shape.

The way it is now, it renders as squares with rounded corners when the size gets bigger (ie 120x120).

**Comment by uttesh** [comment]
@josteinhanssen thanks for the input, we will update that in next release.

**Comment by oglematt** [comment]
@uttesh, When can we expect to see this change? I'd be happy to put it together in a PR, but it's quite literally a single line change from 30px to 50%. If you'd like me to make the adjustment and submit a PR, please let me know. Thanks!

**Comment by uttesh** [comment]
@oglematt thanks , that property is already updated in library, may be i missed to update in the read me page/file, i will update now.

**Comment by oglematt** [comment]
@uttesh, Thanks for the reply. I see that it's on master, but it doesn't appear to have made it to a release. I used bower and that shows that the border radius is still set to 30% and the latest release (4.0.0) also shows 30%.

**Comment by uttesh** [comment]
oh thanks @oglematt i will update the bower and npm libs

**Comment by oglematt** [comment]
@uttesh, Fantastic. Thank you!
